baseURL = "https://tybearder.com/"
languageCode = "en-us"
title = "Tybearder"
theme = "newsroom"
author = "Andrea Bredice"
copyright = "Copyright © 2020, theme made by Weru and the Hugo Authors; all rights reserved."
canonifyurls = true
paginate = 5
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses=true
pygmentsOptions = "linenos=table"

[params]