baseURL = "https://tybearder.com/"
languageCode = "en-us"
title = "Tybearder"
theme = "newsroom"
author = "Andrea Bredice"
copyright = "Copyright © 2020, theme made by Weru and the Hugo Authors; all rights reserved."
canonifyurls = true
paginate = 5
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses=true
pygmentsOptions = "linenos=table"

[params]

    author               = "Andrea Bredice"
    title                = "Tybearder - type, read and have a beard"
    sitename             = "Tybearder - type, read and have a beard"
    description          = "Tybearder is a place where I share all the story I type. Storytelling, traveling and artwork, all made by my beard."               # Max 160 characters show in search results
    images               = ["turin.jpg"]
    homepage             = "home"
    #og_image = "/images/preview.png"
    favicon              = "favicon-16x16.png"

    github = "https://github.com/dasher7"
    facebook = "https://www.facebook.com/andrebredi"
    twitter = "@andreabredi"
    instagram = "@andrea_bredice"